#!/usr/bin/env python3
"""Render ZIPTIDE's durable CI verdict file from GitHub Actions job results."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

ALLOWED_RESULTS = {
    "success",
    "failure",
    "cancelled",
    "skipped",
    "neutral",
    "timed_out",
    "action_required",
    "stale",
    "startup_failure",
    "unknown",
}
EXIT_OK = 0
EXIT_INVALID = 2


@dataclass(frozen=True)
class Verdict:
    overall: str
    editmode: str
    android: str
    contract_reports: str

    @property
    def is_green(self) -> bool:
        return self.overall == "GREEN"


def normalize_result(value: str) -> str:
    normalized = (value or "unknown").strip().lower()
    return normalized if normalized in ALLOWED_RESULTS else "unknown"


def calculate_verdict(editmode: str, android: str, contract_reports: str) -> Verdict:
    editmode = normalize_result(editmode)
    android = normalize_result(android)
    contract_reports = normalize_result(contract_reports)
    overall = (
        "GREEN"
        if editmode == "success" and android in {"success", "skipped"}
        else "RED"
    )
    return Verdict(overall, editmode, android, contract_reports)


def render(
    *,
    repository: str,
    branch: str,
    sha: str,
    run_id: str,
    run_attempt: str,
    run_url: str,
    event_name: str,
    workflow_name: str,
    editmode: str,
    android: str,
    contract_reports: str,
    recorded_at_utc: str,
) -> str:
    verdict = calculate_verdict(editmode, android, contract_reports)
    payload = {
        "schemaVersion": 1,
        "overall": verdict.overall,
        "repository": repository,
        "branch": branch,
        "testedSha": sha,
        "workflow": workflow_name,
        "runId": str(run_id),
        "runAttempt": str(run_attempt),
        "runUrl": run_url,
        "event": event_name,
        "recordedAtUtc": recorded_at_utc,
        "results": {
            "unityEditMode": verdict.editmode,
            "androidApk": verdict.android,
            "projectContractReports": verdict.contract_reports,
        },
        "interpretation": {
            "greenRequires": "Unity EditMode success and Android success when Android ran.",
            "androidSkipped": "Expected for ordinary terry-local-wip push runs.",
            "contractReports": "Informational and non-blocking.",
            "currentWhen": (
                "The live branch head is testedSha, or is the direct generated verdict-only "
                "child of testedSha."
            ),
        },
    }
    short_sha = sha[:12]
    lines = [
        "<!-- GENERATED BY .github/workflows/ci.yml. DO NOT EDIT MANUALLY. -->",
        "# CI Verdict",
        "",
        f"**{verdict.overall}** for `{short_sha}` on `{branch}`.",
        "",
        "```json",
        json.dumps(payload, indent=2, sort_keys=True),
        "```",
        "",
        "| Check | Result | Verdict role |",
        "|---|---|---|",
        f"| Unity EditMode tests | `{verdict.editmode}` | Required |",
        f"| Android APK | `{verdict.android}` | Required when run; normally skipped on branch pushes |",
        f"| Project contract reports | `{verdict.contract_reports}` | Informational, non-blocking |",
        "",
        f"Workflow run: {run_url}",
        "",
        "The recorder writes only when the tested SHA is the live branch head immediately "
        "before the generated verdict commit. After a successful write, the live head is the "
        "direct verdict-only child of `testedSha`. Any later normal commit makes this verdict "
        "stale until that commit's CI run records its own verdict.",
        "",
    ]
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repository", required=True)
    parser.add_argument("--branch", required=True)
    parser.add_argument("--sha", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--run-attempt", default="1")
    parser.add_argument("--run-url", required=True)
    parser.add_argument("--event-name", required=True)
    parser.add_argument("--workflow-name", default="CI")
    parser.add_argument("--editmode-result", required=True)
    parser.add_argument("--android-result", required=True)
    parser.add_argument("--contract-result", required=True)
    parser.add_argument("--recorded-at-utc")
    args = parser.parse_args(argv)

    if len(args.sha.strip()) < 7:
        print("CI_VERDICT_ERROR sha must contain at least 7 characters.")
        return EXIT_INVALID
    if args.branch != "terry-local-wip":
        print("CI_VERDICT_ERROR branch must be terry-local-wip.")
        return EXIT_INVALID

    recorded = args.recorded_at_utc or datetime.now(timezone.utc).isoformat()
    content = render(
        repository=args.repository,
        branch=args.branch,
        sha=args.sha.strip(),
        run_id=args.run_id,
        run_attempt=args.run_attempt,
        run_url=args.run_url,
        event_name=args.event_name,
        workflow_name=args.workflow_name,
        editmode=args.editmode_result,
        android=args.android_result,
        contract_reports=args.contract_result,
        recorded_at_utc=recorded,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(
        "CI_VERDICT_WRITTEN "
        f"overall={calculate_verdict(args.editmode_result, args.android_result, args.contract_result).overall} "
        f"sha={args.sha.strip()} output={args.output}"
    )
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
